// frontend-svelte/src/lib/components/LayerNode.svelte
<script lang="ts">
	import { Handle, Position, type NodeProps } from '@xyflow/svelte';
	import type { NodeWithLayout, Node, Edge } from '$lib/types';
	import { NodeColors } from '$lib/utils/utils';
	import * as Accordion from '$lib/components/ui/accordion';
	import * as api from '$lib/api';
	import { createGraph } from '$lib/graph.svelte';

	interface $$Props extends NodeProps {
		data: NodeWithLayout;
	}
	let { data }: $$Props = $props();
	let graph = createGraph();
	
	function handleExpand() {
		api.expandNode(data.id).then((data) => {
			graph.setNodes(data.nodes);
			graph.setEdges(data.edges);
		});
	}
	
</script>

<Handle id={`${data.id}-target`} type="target" position={data.layout_horizontal ? Position.Left : Position.Top} />
<Handle id={`${data.id}-source`} type="source" position={data.layout_horizontal ? Position.Right : Position.Bottom} />

<div
	class="p-4 wrapper bg-white"
	class:tutorial_cnn_layer={data.tutorial_node}
	style:background-color={NodeColors[data.layer_type]}
>
	<h2 class="text-lg font-bold">{data.name}</h2>
	
	{#if !data.is_leaf}
		<button class="expand-button" onclick={handleExpand}></button>
	{/if}

	<Accordion.Root class="w-full" multiple>
		<Accordion.Item value="details">
			<Accordion.Trigger>Details</Accordion.Trigger>
			<Accordion.Content>
				<ul>
					{#if data.layer_type}
						<li><b>Layer :</b> {data.layer_type}</li>
					{/if}
					{#if data.input_shape}
						<li><b>Input :</b> ({data.input_shape.toString()})</li>
					{/if}
					{#if data.kernel_size}
						<li><b>Kernel Shape :</b> ({data.kernel_size.toString()})</li>
					{/if}
					{#if data.out_edge_weight}
						<li><b>Kernel # :</b> {data.out_edge_weight.length}</li>
					{/if}
					{#if data.output_shape}
						<li><b>Output :</b> ({data.output_shape.toString()})</li>
					{/if}
				</ul>
			</Accordion.Content>
		</Accordion.Item>
	</Accordion.Root>
</div>

<style>
	.wrapper {
		border-radius: 20px;
		border: 1px solid #aaa;
	}
	
	.expand-button {
		width: 10px;
		height: 10px;
		background-color: #aaa;
		border-radius: 50%;
		position: absolute;
		top: 20px;
		right: 20px;
	}
</style>

// activation_pathway_analysis_tool_frontend/src/components/LayerNode.tsx
import React from 'react';
import { Handle, NodeProps, Position } from 'reactflow';
import { Node } from '../types'
import { NodeColors } from '../utils';
import * as api from '../api'
import { useAppDispatch } from '../app/hooks'
import { Card, Button, Accordion } from 'react-bootstrap';
import LayerActivations from './LayerActivations';
import { useAppSelector } from '../app/hooks'
import { current } from '@reduxjs/toolkit';
import LazyAccordionItem from './LazyAccordionItem';
import ScatterPlot from './ScatterPlot';
import NodeImageDistances from './NodeImageDistances';
import NodeActivationHeatmap from './NodeActivationHeatmap';
import NodeActivationMatrix from './NodeActivationMatrix';



function LayerNode({ id, data }: { id: string, data: Node }) {
    return (
        <div style={{
            display: 'flex',
            flexDirection: 'column',
            backgroundColor: NodeColors[data.layer_type],
            borderRadius: 10,
            border: '1px solid #aaa',
        }}>
            <Handle type="target" position={data.layout_horizontal?Position.Left:Position.Top} />
            <Card>
                <Card.Body style={{
                    display: 'flex',
                    flexDirection: 'column',
                }}>
                    <Card.Title>{data.name}</Card.Title>
                    <NodeActivationHeatmap node={data} width={350} height={600} />
                    <NodeActivationMatrix node={data} width={350} height={350} />
                    <Accordion alwaysOpen flush>
                        <LazyAccordionItem header="Details" eventKey="0">
                            <ul>
                                <li> <b>Layer :</b> {data.layer_type} </li>
                                <li> <b>Input :</b> ({data.input_shape.toString()}) </li>
                                <li> <b>Kernel Shape :</b> ({data.kernel_size.toString()}) </li>
                                <li> <b>Output :</b> ({data.output_shape.toString()}) </li>
                            </ul>
                        </LazyAccordionItem>
                        <LazyAccordionItem header="Activations" eventKey="1">
                            <LayerActivations node={data} />
                        </LazyAccordionItem>
                        <LazyAccordionItem header="Activation Distances" eventKey="2">
                            <NodeImageDistances node={data} />
                        </LazyAccordionItem>
                    </Accordion>
                </Card.Body>
            </Card>
            <Handle type="source" position={data.layout_horizontal?Position.Right:Position.Bottom} />
        </div>
    );
}

export default LayerNode;
